[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "python-virtualized-runtimes"
version = "0.1.0"
authors = [
    { name="Nicholas Brunet", email="nickjbrunet@outlook.com" },
]
description = "TODO"
readme = "README.md"
requires-python = ">=3.11"
classifiers = []
dependencies = []

[project.urls]
Homepage = "https://github.com/NicholasBrunet/python-bytecode"

[tool.setuptools.packages.find]
where = ["src"]