
MAX_VTHREADS: int = 16
MAX_VSTORAGE_GLOBALS: int = 256
MAX_VSTORAGE_CONSTANTS: int = 1024
MAX_VFRAME_LOCALS: int = 256
MAX_VFRAME_EVALUATION_STACK: int = 256

MAX_SCOPE_GLOBALS: int = MAX_VSTORAGE_GLOBALS
MAX_SCOPE_LOCALS: int = MAX_VFRAME_LOCALS
MAX_SCOPE_PRIMITIVES: int = MAX_VSTORAGE_CONSTANTS
MAX_SCOPE_STACK: int = MAX_VFRAME_EVALUATION_STACK
MAX_SCOPE_INSTRUCTIONS: int = 256
MAX_SCOPE_CODE_OBJECTS: int = 64

BUILTINS_MAP: dict[str, int] = {
    "math": 0, 
    "math.add": 1
}

SCOPE_MODULE: int = 0
SCOPE_FUNCTION: int = 1